# custom_config_b.yaml file
PREDICT_LEN: 50   
CLUSTER_PERIOD: 7    
PRERROR: 2    
SPLIT_BACKWARD: 50
SLIDE_BACKWARD_STEP: 50
PUR_TIME_PER_DAY_UNNORMAL_THRESHOLD: 8
PUR_PERIOD: 1
SLIDE_STEP: 7