from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')
nltk.download('opinion_lexicon')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')

stopwords = set(stopwords.words('english')) # nltk data
include_stopwords = {'dear', 'regards', 'must', 'would', 'also', 'app','application'}
exclude_stopwords = {'against', "don't", "didn't", "doesn't", "can't", "wouldn't","aren't","not","hasn't","wasn't","won't","hadn't"}
stopwords |= include_stopwords
stopwords -= exclude_stopwords

dirty_words = ['qq','cc','lol','dm', 'vl', 'cock', 'l', 'c', 'shit', 'cobs']


custom_dict = {"đăng nhap":"đăng nhập",
               "đang nhập":"đăng nhập",
               "ko"      : "không",
               "hđ"      : "hợp đồng",
               "k"        : "không",
               "dky"     : "đăng ký",
               "dk": "đăng ký",
               "dki":"đăng ký",
               "đki":"đăng ký",
               "rat":"rất",
               "ung dung":"ứng dụng",
               "ko":"không",
               "b":"bọn",
               "mất day":"mất dạy",
               "nh":"ngân hàng",
               "đt":"điện thoại",
               "yc":"yêu cầu", 
               "nv":"nhân viên",
               "hs":"hồ sơ",
               "đc":"được",
               "mn":"mọi người", 
              "pis":"biết",
               "ms":"mới",
               "g" :"giờ",
               "sd":"sử dụng",
              "kh.":"khách hàng.",
               "kh":"khách hàng",
               "qq":"shit",
               "đk":"được", 
               "vl":"", 
               "méo":"không",
               "cặc":"tồi", 
               "lồn":"tồi", 
               "dc":"được",  
               "dt":"điện thoại", 
               "l":"tồi",
               "mk":"mật khẩu", 
               "đ kí":"đăng ký",  
               "ngta":" người ta",
               "r":" rồi",
               "k":" không", 
               "lol":"", 
               "tk":"tài khoản", 
               "tn":"tin nhắn", 
               "đăng kí":"đăng ký", 
               "cccd":"căn cước công dân",
               "sdt":"số điện thoại", 
               "e":"em", 
               "vãi":"", 
               "y/c":" yêu cầu", 
               "đăng kí":"đăng ký", 
               "m":"",
               "t":"",
               "mh":"mình", 
               "đang ký":"đăng ký", 
               "đang nhập":"đăng nhập", 
               "9 xác":"chính xác", 
               "cmt":"chứng minh nhân dân", 
               "nc":"nói chuyện",
               "hok":"không", 
               "ck":"chuyển khoản", 
               "háng":"", 
               "đku":"đăng ký", 
               "s":" sao", 
               "ah":"ạ", 
               "cc":"tồi", 
               "j":"gì", 
               "moẹ":"",
               "hk":" không", 
               "đang nhap":" đăng nhập",
               "éo":" không",
               "kô":" không", 
               "âu cơ":"ok",
               "cức":" tồi", 
               "áp":" app", 
               "ap":" app",
               "quần què":" không được", 
               "rr":"",
               "vkl":"", 
               "tg":" thời gian", 
               "nhu lon":"tồi",
               "ak":"ạ", 
               "ffc":"được", 
               "cc":"tồi",
               "login":"đăng nhập", 
               "đăg ký":"đăng ký",               
               "wtf":"tệ", 
               "z":"vậy", 
               "đn":" đăng nhập", 
               "cg":"cũng", 
               "mat khẩu":"mật khẩu",
               "bnhiu":"bao nhiêu",
               "add":"ad",
               "l ồ n":"tồi", 
               "củ lìn":"tồi",
               "thẻ td":"thẻ tín dụng",
               "m,n":"mọi người",    
               "ng":"người",  
               "n.h":"ngân hàng",
               "nh":" ngân hàng",
               "pơ phếch":"perfect",
               "<3":"love it",
               ":v":"",
               "good chóp":"good job",
               "Hayy":"hay",
               "dăng ký":"đăng ký",
               "thê tín dụng":"thẻ tín dụng",
               "tot":"tốt",
               "cam thay":"cảm thấy",
               "ngan hang":"ngân hàng",
               "rat la":"rất là",
               "huu it":"hữu ích",
               "bt":"bình thường",
               "3*":"3 sao",
               "1*":"1 sao",
               "0*":"0 sao",
               "ghi no":"ghi nợ",
               "acc":"tài khoản",
               "ac": "tài khoản",
               "ae":"bạn",
               "bai":"tạm biệt",
               "bla":"vân vân",
               "ccc":"tồi",
               "1p":"1 phút",
               "hđh": "hệ điều hành",
               "hdh": "hệ điều hành",
               "alo": "gọi",
               "ok":"okay",
               "nqq":"kém",
                "đt":"điện thoại",
                "K":"không"  ,           
                "đc":"được",
                "địh":"định",
                "ko":"không",
                "dc":"được",
                "minh":"mình",
                "mik":"mình",
                "gthieu":"giới thiệu",
                "toi":"tôi",
                "khong":"không",
                "nhan":"nhận",
                "duoc":"được",
                "diem thuong":"điểm thưởng",
                "acc":"account",
                "std":"số điện thoại",
                "chuyên tiền":"chuyển tiền",
                "ko nap":"không nạp",
                "tien":"tiền",
                "e":"em",
                "tr":"triệu",
                "cc":"shit",
                "cccc":"shit",
                "lam":"làm",
                "dang hoang":"đàng hoàng",
                "chang":"chẳng",
                "chuyen nghiep":"chuyên nghiệp",
                "qua chan":"quá chán",
                "kahwcs":"khắc",
                "chia sẽ":"chia sẻ",
                "bt":"biết",
                "std":"số điện thoại",
                "ad":"admin",
                "kh":"khách hàng",
                "zo":"vô",
                "apk":"app",
                "b":"bạn",
                "cguyeenr":"chuyển",
                "bb":"bạn bè",
                "sét":"xét",
                "cứt":"shit",
                "tian":"tín",
                "gd":"giao dịch",
                "đơ":"không hoạt động",
                "DIỆN":"diện",
                "sync":"đồng bộ",
                "tk":"tài khoản",
                "trg":"trường",
                "mat khẩu":"mật khẩu",
                "noti":"thông báo",
                "kho xai":"khó xài",
                "thanh toan":"thanh toán",
                "hoa don":"hóa đơn",
                "ung dung":"ứng dụng",
                "nhằg":"nhằng",
                "mơi":"mới",
                "áp":"app",
                "sotp":"smart otp",
                "ver1":"version 1",
                "smartotp":"smart otp",
                "vs":"với",
                "cãi":"cải",
                "vd":"ví dụ",
                "cccd":"căn cước công dân",
                "mói":"mới",
                "quắc":"quá",
                "m":"muốn",
                "hoàng":"hoàn",
                "suốtt":"suốt",
                "lich su":"lịch sử",
                "chi tiet":"chi tiết",
                "noi dung":"nội dung",
                "thi":"thì",
                "it":"ít",
                "hon":"hơn",
                "phan":"phần",
                "nhieu":"nhiều",
                "mk":"mật khẩu",
                "ck":"chuyển khoản",
                "mat khau":"mật khẩu",
                "dang nhap":"đăng nhập",
                "khong doi":"không đổi",
                "dâu":"đâu",
                "đôi":"đổi",
                "mât khâu":"mật khẩu",
                "vao":"vào",
                "su dung":"sử dụng",
                "cons":"coin",
                "j":"gì",
                "méo":"không",
                "zây":"dậy",
                "nap":"nạp",
                "h":"giờ",
                "hòn":"hoàn",
                "hó":"hóa",
                "c":"shit",
                "ụa":"ủa",
                "điểm coi":"điểm coin",
                "r":"rồi",
                "ngận":"nhận",
                "chuyển khoan":"chuyển khoản",
                "giòe":"giờ",
                "s v":"sao vậy",
                "xog":"xong",
                "lmj":"làm gì",
                "khắng":"khắc",
                "kog":"không",
                "lol":"shit",
                "cùi":"không tốt",
                "nta":"người ta",
                "gt":"giới thiệu",
                "icon":"coin",
                "cont":"coin",
                "100ngan":"100 ngàn",
                "2ngay":"2 ngày",
                "lối":"lỗi",
                "kh":"không",
                "sử lý":"xử lý",
                "điệ":"điện",
                "nạp dk":"nạp được",
                "hfafng":"hàng",
                "mjk":"mình",
                "dụnh":"dụng",
                "s":"sao",
                "mh":"mình",
                "cặc":"tệ",
                "cức":"tệ",
                "cứt":"tệ",
                "tuyet voi":"tuyệt vời",
                "rat":"rất",
                "hayy":"hay",
                "okjie":"okay",
                "totttttt":"tốt",
                "cap nhat":"cập nhật",
                "tien lợi":"tiện lợi",
                "tam ôn":"tạm ổn",
                "oke":"okay",
                "mỹ":"my",
                "tiênf":"tiền",
                "Ựng dựng":"ứng dụng",
                "lozz":"shit",
                "chúp":"chụp",
                "đell":"không"
                }

negative_word =['lỗi','không','chán','shit','tệ','kém','tại sao','sao','đơ','lừa','lâu','chậm','lag','bịp','kiểu gì','là sao','tự ý','phức tạp','tẻ nhạt','khó dùng','bất tiện']


custom_dict1 = { "đăng n,hập":"đăng_nhập",
                 "đang nhập":"đăng_nhập", 
                 "ko": 'không',
                 "k": "không",
                 "hok":"không", 
                "hk":"không", 
                "kô":"không", 
                # "k": "không", 
                "hđ":"hợp_đồng",
                "dky": "đăng_ký",
                "đ kí": "đăng_ký", 
                "đăng kí":"đăng_ký",
                "đang ký":"đăng_ký", 
                "đang kí":"đăng_ký", 
                "đăg ký":"đăng_ký",
                "đku":"đăng_ký", 
                "dk":"đăng_ký", 
                'kí':'ký',
                "đk":"được", # dky?
                "dc": "được", 
                # "ko":"không",
                "b":"bọn",
                "mất day": "mất_dạy",
                "nh": "ngân_hàng ",
                'n . h':"ngân_hàng ",
                'n.h':"ngân_hàng ",
                "đt":"điện_thoại",
                "yc":"yêu_cầu", # avoid kyc/ekyc
                "nv":"nhân_viên",
                "hs": "hồ_sơ",
                "đc":"được",
                "mn":"mọi_người", 
                "pis":"biết",
                "ms":"mới",
                "g":" giờ ",
                "sd":"sử_dụng",
                "kh":"khách_hàng",
                "qq":"lời_tục",
                "l":" lời_tục,",
                "vl":"lời_tục", 
                "méo":"lời_tục",
                "cặc":"lời_tục", 
                "lồn":"lời_tục", 
                "lol": "lời_tục", 
                "wtf":"lời_tục", 
                "vãi":"lời_tục", 
                "l ồ n":"lời_tục", 
                'củ lìn':"lời_tục",
                "m":"lời_tục",
                "quần què": "lời_tục", 
                "cức":"lời_tục", 
                "t":"lời_tục",
                "éo":"lời_tục",
                "moẹ":"lời_tục",
                "rr": "lời_tục",
                "vkl":"lời_tục",
                "cc":"lời_tục", 
                "háng":"lời_tục",
                "dt":"điện_thoại", 
                "mk" : "mật_khẩu", 
                "ngta": "người_ta",
                "r": "rồi",
                "tk": "tài_khoản", 
                "tn":"tin_nhắn", 
                "căn cước":"cccd",
                "sdt":"số_điện_thoại", 
                "e":"em", 
                "y/c":"yêu_cầu", 
                "mh":"mình", 
                "9 xác": "chính_xác", 
                "cmt":"cmnd", 
                "nc":"nói_chuyện",
                "ck":"chuyển_khoản", 
                "s":"sao", 
                "ah":"ạ", 
                "j":"gì", 
                "đang nhap":"đăng_nhập",
                "âu cơ":"ok",
                "áp":"app", 
                'ap':'app',
                "tg":"thời_gian", 
                "nhu lon":"như lời_tục",
                "ak":"ạ", 
                "ffc":"được", 
                "login":"đăng_nhập", 
                "chứng minh nhân dân":"cmnd",
                "z":"vậy", 
                "đn":"đăng_nhập", 
                "cg":"cũng", 
                "mat khẩu":"mật_khẩu",
                "bnhiu":"bao nhiêu",
                "add":"ad",
                'thẻ tín dụng': "thẻ_tín_dụng",  
                'thẻ td': "thẻ_tín_dụng",
                # 'thẻ':"thẻ_tín_dụng",
                'm,n': "mọi_người",    
                'ng': 'người',
                'pơ phếch': 'perfect',
                'pơ phệch': 'perfect',
                '<3': 'tốt',
                ':v': '',
                'good chóp': 'tốt',
                'khuôn mặt':'khuôn_mặt',
                'làm viec':'làm_việc',
                'update':'cập_nhật'
                                }